
import Link from 'next/link'
import './globals.css'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <header>
          <Link href="/">HOME</Link>
          <Link href='/test'>Test</Link> {/* 라우터가 폴더를 가르키고 있음 즉 pages.js라는 파일이 열림 레이아웃 프레임 페이지가 레이아웃 프레임 안에 들어감 */}
          <Link href="/js"> Js</Link>
        </header>

        <Context>
        <main>
        {children} {/* 컨텐츠 */}
        </main>
        </Context>
        
      </body>
    </html>
  )
}
